Attribute VB_Name = "MLCID"
Option Explicit

Public Enum ELCID
    lcid_ar = &H1
    lcid_BG = &H2
    lcid_CA = &H3
    lcid_zh_Hans = &H4
    lcid_CS = &H5
    lcid_da = &H6
    lcid_de = &H7
    lcid_el = &H8
    lcid_en = &H9
    lcid_es = &HA
    lcid_FI = &HB
    lcid_fr = &HC
    lcid_he = &HD
    lcid_HU = &HE
    lcid_is_ = &HF
    lcid_it = &H10
    lcid_ja = &H11
    lcid_ko = &H12
    lcid_nl = &H13
    lcid_NO = &H14
    lcid_PL = &H15
    lcid_PT = &H16
    lcid_rm = &H17
    lcid_ro = &H18
    lcid_ru = &H19
    lcid_hr = &H1A
    lcid_SK = &H1B
    lcid_sq = &H1C
    lcid_SV = &H1D
    lcid_TH = &H1E
    lcid_TR = &H1F
    lcid_ur = &H20
    lcid_ID = &H21
    lcid_uk = &H22
    lcid_BE = &H23
    lcid_sl = &H24
    lcid_ET = &H25
    lcid_LV = &H26
    lcid_LT = &H27
    lcid_tg = &H28
    lcid_fa = &H29
    lcid_vi = &H2A
    lcid_hy = &H2B
    lcid_az = &H2C
    lcid_eu = &H2D
    lcid_hsb = &H2E
    lcid_MK = &H2F
    lcid_st = &H30
    lcid_ts = &H31
    lcid_TN = &H32
    lcid_VE = &H33
    lcid_xh = &H34
    lcid_zu = &H35
    lcid_AF = &H36
    lcid_ka = &H37
    lcid_FO = &H38
    lcid_Hi = &H39
    lcid_MT = &H3A
    lcid_SE = &H3B
    lcid_ga = &H3C
    'lcid_yi = &H3D    ', Reserved
    lcid_ms = &H3E
    lcid_kk = &H3F
    lcid_ky = &H40
    lcid_sw = &H41
    lcid_tk = &H42
    lcid_uz = &H43
    lcid_TT = &H44
    lcid_bn = &H45
    lcid_pa = &H46
    lcid_gu = &H47
    lcid_or_ = &H48
    lcid_ta = &H49
    lcid_te = &H4A
    
    lcid_kn = &H4B
    lcid_ML = &H4C
    lcid_as_ = &H4D
    lcid_mr = &H4E
    lcid_sa = &H4F
    lcid_mn = &H50
    lcid_BO = &H51
    lcid_cy = &H52
    lcid_km = &H53
    lcid_Lo = &H54
    lcid_MY = &H55
    lcid_GL = &H56
    lcid_kok = &H57
    'lcid_mni = &H58   ', Reserved
    lcid_sd = &H59
    lcid_syr = &H5A
    lcid_si = &H5B
    lcid_Chr = &H5C
    lcid_iu = &H5D
    lcid_am = &H5E
    lcid_tzm = &H5F
    lcid_ks = &H60
    lcid_ne = &H61
    lcid_fy = &H62
    lcid_ps = &H63
    lcid_fil = &H64
    lcid_dv = &H65
    'lcid_bin = &H66   ', Reserved
    lcid_ff = &H67
    lcid_ha = &H68
    'lcid_ibb = &H69   ', Reserved
    lcid_yo = &H6A
    
    lcid_quz = &H6B
    lcid_nso = &H6C
    lcid_BA = &H6D
    lcid_lb = &H6E
    lcid_kl = &H6F
    lcid_ig = &H70
    'lcid_kr = &H71   ', Reserved
    lcid_OM = &H72
    lcid_ti = &H73
    lcid_gn = &H74
    lcid_haw = &H75
    'lcid_la = &H76   ', Reserved
    'lcid_SO = &H77   ', Reserved
    lcid_ii = &H78
    'lcid_pap = &H79   ', Reserved
    lcid_arn = &H7A
    '0x007B  Neither defined nor reserved
    lcid_moh = &H7C
    '0x007D  Neither defined nor reserved
    lcid_br = &H7E
    '0x007F  Reserved for invariant locale behavior
    lcid_ug = &H80
    lcid_mi = &H81
    lcid_oc = &H82
    lcid_CO = &H83
    lcid_gsw = &H84
    lcid_sah = &H85
    lcid_qut = &H86
    lcid_RW = &H87
    lcid_wo = &H88
    '0x0089  Neither defined nor reserved
    '0x008A  Neither defined nor reserved
    
    '0x008B  Neither defined nor reserved
    lcid_prs = &H8C
    '0x008D  Neither defined nor reserved
    '0x008E  Neither defined nor reserved
    '0x008F  Neither defined nor reserved
    '0x0090  Neither defined nor reserved
    lcid_gd = &H91
    lcid_ku = &H92
    'lcid_quc = &H93    ', Reserved
    lcid_ar_sa = &H401
    lcid_BG_BG = &H402
    lcid_CA_es = &H403
    lcid_zh_TW = &H404
    lcid_CS_CZ = &H405
    lcid_da_DK = &H406
    lcid_de_DE = &H407
    lcid_el_GR = &H408
    lcid_en_US = &H409
    lcid_es_ES_tradnl = &H40A
    lcid_FI_FI = &H40B
    lcid_fr_fr = &H40C
    lcid_he_IL = &H40D
    lcid_HU_HU = &H40E
    lcid_is_IS = &H40F
    lcid_it_it = &H410
    lcid_ja_JP = &H411
    lcid_ko_kr = &H412
    lcid_nl_nl = &H413
    lcid_nb_NO = &H414
    lcid_PL_PL = &H415
    lcid_PT_br = &H416
    lcid_rm_CH = &H417
    lcid_ro_ro = &H418
    lcid_ru_ru = &H419
    lcid_hr_hr = &H41A
    lcid_SK_SK = &H41B
    lcid_sq_AL = &H41C
    lcid_SV_SE = &H41D
    lcid_TH_TH = &H41E
    lcid_TR_TR = &H41F
    lcid_ur_PK = &H420
    lcid_ID_ID = &H421
    lcid_uk_UA = &H422
    lcid_BE_By = &H423
    lcid_sl_si = &H424
    lcid_ET_EE = &H425
    lcid_LV_LV = &H426
    lcid_LT_LT = &H427
    lcid_tg_Cyrl_TJ = &H428
    lcid_fa_IR = &H429
    lcid_vi_VN = &H42A
    lcid_hy_am = &H42B
    lcid_az_Latn_az = &H42C
    lcid_eu_es = &H42D
    lcid_hsb_de = &H42E
    lcid_MK_MK = &H42F
    lcid_st_ZA = &H430
    lcid_ts_ZA = &H431
    lcid_TN_ZA = &H432
    lcid_VE_ZA = &H433
    lcid_xh_ZA = &H434
    lcid_zu_ZA = &H435
    lcid_AF_ZA = &H436
    lcid_ka_GE = &H437
    
    lcid_FO_FO = &H438
    lcid_hi_IN = &H439
    lcid_MT_MT = &H43A
    lcid_SE_NO = &H43B
    lcid_yi_1 = &H43D
    lcid_ms_MY = &H43E
    lcid_kk_KZ = &H43F
    lcid_ky_KG = &H440
    lcid_sw_KE = &H441
    lcid_tk_TM = &H442
    lcid_uz_Latn_uz = &H443
    lcid_TT_ru = &H444
    lcid_bn_IN = &H445
    lcid_pa_IN = &H446
    lcid_gu_IN = &H447
    lcid_or_IN = &H448
    lcid_ta_IN = &H449
    lcid_te_IN = &H44A
    lcid_kn_IN = &H44B
    lcid_ml_IN = &H44C
    lcid_as_IN = &H44D
    lcid_mr_IN = &H44E
    lcid_sa_IN = &H44F
    lcid_mn_mn = &H450
    lcid_BO_CN = &H451
    lcid_cy_GB = &H452
    lcid_km_KH = &H453
    lcid_Lo_la = &H454
    lcid_MY_MM = &H455
    lcid_GL_es = &H456
    lcid_kok_IN = &H457
    'lcid_mni_IN = &H458  ', Reserved
    
    'lcid_sd_Deva_IN = &H459  ', Reserved
    lcid_syr_SY = &H45A
    lcid_si_LK = &H45B
    lcid_Chr_Cher_US = &H45C
    lcid_iu_Cans_CA = &H45D
    lcid_am_ET = &H45E
    lcid_tzm_Arab_MA = &H45F
    lcid_ks_Arab = &H460
    lcid_ne_NP = &H461
    lcid_fy_nl = &H462
    lcid_ps_AF = &H463
    lcid_fil_PH = &H464
    lcid_dv_MV = &H465
    'lcid_bin_NG = &H466  ', Reserved
    'lcid_ff_NG = &H467  ', ff_Latn_NG
    lcid_ha_Latn_NG = &H468
    'lcid_ibb_NG = &H469  ', Reserved
    lcid_yo_NG = &H46A
    lcid_quz_BO = &H46B
    lcid_nso_ZA = &H46C
    lcid_BA_ru = &H46D
    lcid_lb_LU = &H46E
    lcid_kl_GL = &H46F
    lcid_ig_NG = &H470
    lcid_kr_Latn_NG = &H471
    lcid_OM_ET = &H472
    lcid_ti_ET = &H473
    lcid_gn_PY = &H474
    lcid_haw_US = &H475
    lcid_la_VA = &H476
    lcid_SO_SO = &H477
    lcid_ii_CN = &H478
    
    'lcid_pap_29 = &H479  ', Reserved
    lcid_arn_CL = &H47A
    lcid_moh_CA = &H47C
    lcid_br_fr = &H47E
    lcid_ug_CN = &H480
    lcid_mi_NZ = &H481
    lcid_oc_fr = &H482
    lcid_CO_fr = &H483
    lcid_gsw_fr = &H484
    lcid_sah_ru = &H485
    'lcid_qut_GT = &H486  ', Reserved
    lcid_RW_RW = &H487
    lcid_wo_SN = &H488
    lcid_prs_AF = &H48C
    'lcid_plt_MG = &H48D  ', Reserved
    'lcid_zh_yue_HK = &H48E  ', Reserved
    'lcid_tdd_Tale_CN = &H48F  ', Reserved
    'lcid_khb_Talu_CN = &H490  ', Reserved
    lcid_gd_GB = &H491
    lcid_ku_Arab_IQ = &H492
    'lcid_quc_CO = &H493  ', Reserved
    lcid_qps_Ploc = &H501
    lcid_qps_ploca = &H5FE
    lcid_ar_IQ = &H801
    lcid_CA_es_valencia = &H803
    lcid_zh_CN = &H804
    lcid_de_CH = &H807
    lcid_en_GB = &H809
    lcid_es_MX = &H80A
    lcid_fr_BE = &H80C
    lcid_it_CH = &H810
    'lcid_ja_Ploc_JP = &H811  ' = &H, Reserved
    
    lcid_nl_BE = &H813
    lcid_nn_NO = &H814
    lcid_PT_PT = &H816
    lcid_ro_MD = &H818
    lcid_ru_MD = &H819
    lcid_sr_Latn_CS = &H81A
    lcid_SV_FI = &H81D
    lcid_ur_IN = &H820
    '0x0827  Neither defined nor reserved
    'lcid_az_Cyrl_az = &H82C  ', Reserved
    lcid_dsb_de = &H82E
    lcid_TN_BW = &H832
    lcid_SE_SE = &H83B
    lcid_ga_IE = &H83C
    lcid_ms_bn = &H83E
    'lcid_kk_Latn_KZ = &H83F  ', Reserved
    'lcid_uz_Cyrl_uz = &H843  ', Reserved
    lcid_bn_BD = &H845
    lcid_pa_Arab_PK = &H846
    lcid_ta_LK = &H849
    'lcid_mn_Mong_CN = &H850  ', Reserved
    'lcid_BO_BT = &H851  ', Reserved
    lcid_sd_Arab_PK = &H859
    lcid_iu_Latn_CA = &H85D
    lcid_tzm_Latn_DZ = &H85F
    lcid_ks_Deva_IN = &H860
    lcid_ne_IN = &H861
    lcid_ff_Latn_SN = &H867
    lcid_quz_EC = &H86B
    lcid_ti_ER = &H873
    lcid_qps_plocm = &H9FF
    '0x0C00  Locale without assigned LCID if the current user default locale. See section 2.2.1.
    
    lcid_ar_EG = &HC01
    lcid_zh_HK = &HC04
    lcid_de_AT = &HC07
    lcid_en_AU = &HC09
    lcid_es_ES = &HC0A
    lcid_fr_CA = &HC0C
    lcid_sr_Cyrl_CS = &HC1A
    lcid_SE_FI = &HC3B
    lcid_mn_Mong_mn = &HC50
    lcid_DZ_BT = &HC51
    'lcid_tmz_MA = &HC5F  ', Reserved
    lcid_quz_PE = &HC6B
    '0x1000  Locale without assigned LCID if the current user default locale. See section 2.2.1.
    lcid_ar_LY = &H1001
    lcid_zh_SG = &H1004
    lcid_de_LU = &H1007
    lcid_en_CA = &H1009
    lcid_es_GT = &H100A
    lcid_fr_CH = &H100C
    lcid_hr_BA = &H101A
    lcid_smj_NO = &H103B
    lcid_tzm_Tfng_MA = &H105F
    lcid_ar_DZ = &H1401
    lcid_zh_MO = &H1404
    lcid_de_LI = &H1407
    lcid_en_NZ = &H1409
    lcid_es_CR = &H140A
    lcid_fr_LU = &H140C
    lcid_bs_Latn_BA = &H141A
    lcid_smj_SE = &H143B
    lcid_ar_MA = &H1801
    lcid_en_IE = &H1809
    
    lcid_es_pa = &H180A
    lcid_fr_MC = &H180C
    lcid_sr_Latn_BA = &H181A
    lcid_sma_NO = &H183B
    lcid_ar_TN = &H1C01
    lcid_en_ZA = &H1C09
    lcid_es_DO = &H1C0A
    lcid_fr_29 = &H1C0C
    lcid_sr_Cyrl_BA = &H1C1A
    lcid_sma_SE = &H1C3B
    lcid_ar_OM = &H2001
    '0x2008  Neither defined nor reserved
    lcid_en_JM = &H2009
    lcid_es_VE = &H200A
    lcid_fr_RE = &H200C
    lcid_bs_Cyrl_BA = &H201A
    lcid_sms_FI = &H203B
    lcid_ar_YE = &H2401
    'lcid_en_29 = &H2409 ', Reserved
    lcid_es_CO = &H240A
    lcid_fr_CD = &H240C
    lcid_sr_Latn_RS = &H241A
    lcid_smn_FI = &H243B
    lcid_ar_SY = &H2801
    lcid_en_BZ = &H2809
    lcid_es_PE = &H280A
    lcid_fr_SN = &H280C
    lcid_sr_Cyrl_RS = &H281A
    lcid_ar_JO = &H2C01
    lcid_en_TT = &H2C09
    lcid_es_ar = &H2C0A
    lcid_fr_CM = &H2C0C
    
    lcid_sr_Latn_Me = &H2C1A
    '0x3000  Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1.
    lcid_ar_lb = &H3001
    lcid_en_ZW = &H3009
    lcid_es_EC = &H300A
    lcid_fr_ci = &H300C
    lcid_sr_Cyrl_Me = &H301A
    '0x3400  Unassigned LCID locale temporarily assigned to LCID 0x3400. See section 2.2.1.
    lcid_ar_KW = &H3401
    lcid_en_PH = &H3409
    lcid_es_CL = &H340A
    lcid_fr_ML = &H340C
    '0x3800  Unassigned LCID locale temporarily assigned to LCID 0x3800. See section 2.2.1.
    lcid_ar_AE = &H3801
    'lcid_en_ID = &H3809 ', Reserved
    lcid_es_UY = &H380A
    lcid_fr_MA = &H380C
    '0x3C00  Unassigned LCID locale temporarily assigned to LCID 0x3C00. See section 2.2.1.
    lcid_ar_BH = &H3C01
    lcid_en_HK = &H3C09
    lcid_es_PY = &H3C0A
    lcid_fr_HT = &H3C0C
    '0x4000  Unassigned LCID locale temporarily assigned to LCID 0x4000. See section 2.2.1.
    lcid_ar_QA = &H4001
    lcid_en_IN = &H4009
    lcid_es_BO = &H400A
    '0x4400  Unassigned LCID locale temporarily assigned to LCID 0x4400. See section 2.2.1.
    'lcid_ar_Ploc_sa = &H4401 ', Reserved
    lcid_en_MY = &H4409
    lcid_es_SV = &H440A
    '0x4800  Unassigned LCID locale temporarily assigned to LCID 0x4800. See section 2.2.1.
    'lcid_ar_145 = &H4801 ', Reserved
    
    lcid_en_SG = &H4809
    lcid_es_HN = &H480A
    '0x4C00  Unassigned LCID locale temporarily assigned to LCID 0x4C00. See section 2.2.1.
    lcid_en_AE = &H4C09
    lcid_es_NI = &H4C0A
    'lcid_en_BH = &H5009 ', Reserved
    lcid_es_PR = &H500A
    'lcid_en_EG = &H5409 ', Reserved
    lcid_es_US = &H540A
    'lcid_en_JO = &H5809 ', Reserved
    'lcid_es_419 = &H580A ', Reserved
    'lcid_en_KW = &H5C09 ', Reserved
    lcid_es_CU = &H5C0A
    'lcid_en_TR = &H6009 ', Reserved
    'lcid_en_YE = &H6409 ', Reserved
    lcid_bs_Cyrl = &H641A
    lcid_bs_Latn = &H681A
    lcid_sr_Cyrl = &H6C1A
    lcid_sr_Latn = &H701A
    lcid_smn = &H703B
    lcid_az_Cyrl = &H742C
    lcid_sms = &H743B
    lcid_zh = &H7804
    lcid_nn = &H7814
    lcid_bs = &H781A
    lcid_az_Latn = &H782C
    lcid_sma = &H783B
    'lcid_kk_Cyrl = &H783F ', Reserved
    lcid_uz_Cyrl = &H7843
    lcid_mn_Cyrl = &H7850
    lcid_iu_Cans = &H785D
    lcid_tzm_Tfng = &H785F
    
    lcid_zh_Hant = &H7C04
    lcid_nb = &H7C14
    lcid_sr = &H7C1A
    lcid_tg_Cyrl = &H7C28
    lcid_dsb = &H7C2E
    lcid_smj = &H7C3B
    'lcid_kk_Latn = &H7C3F  ', Reserved
    lcid_uz_Latn = &H7C43
    lcid_pa_Arab = &H7C46
    lcid_mn_Mong = &H7C50
    lcid_sd_Arab = &H7C59
    lcid_Chr_Cher = &H7C5C
    lcid_iu_Latn = &H7C5D
    lcid_tzm_Latn = &H7C5F
    lcid_ff_Latn = &H7C67
    lcid_ha_Latn = &H7C68
    lcid_ku_Arab = &H7C92
    '0xF2EE Reserved
    'lcid_fr_15 = &HE40C ', Reserved
    '0xEEEE Reserved
    
End Enum

Public Function ELCID_ToStr(lcid As ELCID) As String
    Dim s As String
    Select Case lcid
    Case lcid_ar:            s = "ar"       '   &H1
    Case lcid_BG:            s = "BG"       '   &H2
    Case lcid_CA:            s = "CA"       '   &H3
    Case lcid_zh_Hans:       s = "zh-Hans"  '   &H4
    Case lcid_CS:            s = "CS"       '   &H5
    Case lcid_da:            s = "da"       '   &H6
    Case lcid_de:            s = "de"       '   &H7
    Case lcid_el:            s = "el"       '   &H8
    Case lcid_en:            s = "en"       '   &H9
    Case lcid_es:            s = "es"       '   &HA
    Case lcid_FI:            s = "FI"       '   &HB
    Case lcid_fr:            s = "fr"       '   &HC
    Case lcid_he:            s = "he"       '   &HD
    Case lcid_HU:            s = "HU"       '   &HE
    Case lcid_is_:           s = "is"       '   &HF
    Case lcid_it:            s = "it"       '   &H10
    Case lcid_ja:            s = "ja"       '   &H11
    Case lcid_ko:            s = "ko"       '   &H12
    Case lcid_nl:            s = "nl"       '   &H13
    Case lcid_NO:            s = "NO"       '   &H14
    Case lcid_PL:            s = "PL"       '   &H15
    Case lcid_PT:            s = "PT"       '   &H16
    Case lcid_rm:            s = "rm"       '   &H17
    Case lcid_ro:            s = "ro"       '   &H18
    Case lcid_ru:            s = "ru"       '   &H19
    Case lcid_hr:            s = "hr"       '   &H1A
    Case lcid_SK:            s = "SK"       '   &H1B
    Case lcid_sq:            s = "sq"       '   &H1C
    Case lcid_SV:            s = "SV"       '   &H1D
    Case lcid_TH:            s = "TH"       '   &H1E
    Case lcid_TR:            s = "TR"       '   &H1F
    Case lcid_ur:            s = "ur"       '   &H20
    Case lcid_ID:            s = "ID"       '   &H21
    Case lcid_uk:            s = "uk"       '   &H22
    Case lcid_BE:            s = "BE"       '   &H23
    Case lcid_sl:            s = "sl"       '   &H24
    Case lcid_ET:            s = "ET"       '   &H25
    Case lcid_LV:            s = "LV"       '   &H26
    Case lcid_LT:            s = "LT"       '   &H27
    Case lcid_tg:            s = "tg"       '   &H28
    Case lcid_fa:            s = "fa"       '   &H29
    Case lcid_vi:            s = "vi"       '   &H2A
    Case lcid_hy:            s = "hy"       '   &H2B
    Case lcid_az:            s = "az"       '   &H2C
    Case lcid_eu:            s = "eu"       '   &H2D
    Case lcid_hsb:           s = "hsb"      '   &H2E
    Case lcid_MK:            s = "MK"       '   &H2F
    Case lcid_st:            s = "st"       '   &H30
    Case lcid_ts:            s = "ts"       '   &H31
    Case lcid_TN:            s = "TN"       '   &H32
    Case lcid_VE:            s = "VE"       '   &H33
    Case lcid_xh:            s = "xh"       '   &H34
    Case lcid_zu:            s = "zu"       '   &H35
    Case lcid_AF:            s = "AF"       '   &H36
    Case lcid_ka:            s = "ka"       '   &H37
    Case lcid_FO:            s = "FO"       '   &H38
    Case lcid_Hi:            s = "Hi"       '   &H39
    Case lcid_MT:            s = "MT"       '   &H3A
    Case lcid_SE:            s = "SE"       '   &H3B
    Case lcid_ga:            s = "ga"       '   &H3C
    'Case lcid_yi:            s = "yi"       '   &H3D    ', Reserved
    Case lcid_ms:            s = "ms"       '   &H3E
    Case lcid_kk:            s = "kk"       '   &H3F
    Case lcid_ky:            s = "ky"       '   &H40
    Case lcid_sw:            s = "sw"       '   &H41
    Case lcid_tk:            s = "tk"       '   &H42
    Case lcid_uz:            s = "uz"       '   &H43
    Case lcid_TT:            s = "TT"       '   &H44
    Case lcid_bn:            s = "bn"       '   &H45
    Case lcid_pa:            s = "pa"       '   &H46
    Case lcid_gu:            s = "gu"       '   &H47
    Case lcid_or_:           s = "or"       '   &H48
    Case lcid_ta:            s = "ta"       '   &H49
    Case lcid_te:            s = "te"       '   &H4A
    '
    Case lcid_kn:            s = "kn"       '   &H4B
    Case lcid_ML:            s = "ML"       '   &H4C
    Case lcid_as_:           s = "as"       '   &H4D
    Case lcid_mr:            s = "mr"       '   &H4E
    Case lcid_sa:            s = "sa"       '   &H4F
    Case lcid_mn:            s = "mn"       '   &H50
    Case lcid_BO:            s = "BO"       '   &H51
    Case lcid_cy:            s = "cy"       '   &H52
    Case lcid_km:            s = "km"       '   &H53
    Case lcid_Lo:            s = "Lo"       '   &H54
    Case lcid_MY:            s = "MY"       '   &H55
    Case lcid_GL:            s = "GL"       '   &H56
    Case lcid_kok:           s = "kok"      '   &H57
    'Case lcid_mni:           s = "mni"      '   &H58   ', Reserved
    Case lcid_sd:            s = "sd"       '   &H59
    Case lcid_syr:           s = "syr"      '   &H5A
    Case lcid_si:            s = "si"       '   &H5B
    Case lcid_Chr:           s = "Chr"      '   &H5C
    Case lcid_iu:            s = "iu"       '   &H5D
    Case lcid_am:            s = "am"       '   &H5E
    Case lcid_tzm:           s = "tzm"      '   &H5F
    Case lcid_ks:            s = "ks"       '   &H60
    Case lcid_ne:            s = "ne"       '   &H61
    Case lcid_fy:            s = "fy"       '   &H62
    Case lcid_ps:            s = "ps"       '   &H63
    Case lcid_fil:           s = "fil"      '   &H64
    Case lcid_dv:            s = "dv"       '   &H65
    'Case lcid_bin:           s = "bin"      '   &H66   ', Reserved
    Case lcid_ff:            s = "ff"       '   &H67
    Case lcid_ha:            s = "ha"       '   &H68
    'Case lcid_ibb:           s = "ibb"      '   &H69   ', Reserved
    Case lcid_yo:            s = "yo"       '   &H6A
    '
    Case lcid_quz:           s = "quz"      '   &H6B
    Case lcid_nso:           s = "nso"      '   &H6C
    Case lcid_BA:            s = "BA"       '   &H6D
    Case lcid_lb:            s = "lb"       '   &H6E
    Case lcid_kl:            s = "kl"       '   &H6F
    Case lcid_ig:            s = "ig"       '   &H70
    'Case lcid_kr:            s = "_kr"      '   &H71   ', Reserved
    Case lcid_OM:            s = "OM"       '   &H72
    Case lcid_ti:            s = "ti"       '   &H73
    Case lcid_gn:            s = "gn"       '   &H74
    Case lcid_haw:           s = "haw"      '   &H75
    'Case lcid_la:            s = "_la"      '   &H76   ', Reserved
    'Case lcid_SO:            s = "_SO"      '   &H77   ', Reserved
    Case lcid_ii:            s = "ii"       '   &H78
    'Case lcid_pap:           s = "pap"      '   &H79   ', Reserved
    Case lcid_arn:           s = "arn"      '   &H7A
    'Case '0x007B  Neither defined nor reserved   :    s =    "7B  Neither defined nor reserved"  '
    Case lcid_moh:           s = "moh"      '   &H7C
    'Case '0x007D  Neither defined nor reserved   :    s =    "7D  Neither defined nor reserved"  '
    Case lcid_br:            s = "br"       '   &H7E
    'Case '0x007F  Reserved for invariant locale behavior :    s =    "7F  Reserved for invariant locale behavior"    '
    Case lcid_ug:            s = "ug"       '   &H80
    Case lcid_mi:            s = "mi"       '   &H81
    Case lcid_oc:            s = "oc"       '   &H82
    Case lcid_CO:            s = "CO"       '   &H83
    Case lcid_gsw:           s = "gsw"      '   &H84
    Case lcid_sah:           s = "sah"      '   &H85
    Case lcid_qut:           s = "qut"      '   &H86
    Case lcid_RW:            s = "RW"       '   &H87
    Case lcid_wo:            s = "wo"       '   &H88
    'Case        '0x0089  Neither defined nor reserved   :    s =    "89  Neither defined nor reserved"  '
    'Case        '0x008A  Neither defined nor reserved   :    s =    "8A  Neither defined nor reserved"  '
    'Case            :    s =    #WERT!  '
    'Case        '0x008B  Neither defined nor reserved   :    s =    "8B  Neither defined nor reserved"  '
    Case lcid_prs:           s = "prs"      '   &H8C
    'Case        '0x008D  Neither defined nor reserved   :    s =    "8D  Neither defined nor reserved"  '
    'Case        '0x008E  Neither defined nor reserved   :    s =    "8E  Neither defined nor reserved"  '
    'Case        '0x008F  Neither defined nor reserved   :    s =    "8F  Neither defined nor reserved"  '
    'Case        '0x0090  Neither defined nor reserved   :    s =    "90  Neither defined nor reserved"  '
    Case lcid_gd:            s = "gd"       '   &H91
    Case lcid_ku:            s = "ku"       '   &H92
    'Case        'lcid_quc   :    s =    "_quc"  '   &H93    ', Reserved
    Case lcid_ar_sa:         s = "ar-sa"    '   &H401
    Case lcid_BG_BG:         s = "BG-BG"    '   &H402
    Case lcid_CA_es:         s = "CA-es"    '   &H403
    Case lcid_zh_TW:         s = "zh-TW"    '   &H404
    Case lcid_CS_CZ:         s = "CS-CZ"    '   &H405
    Case lcid_da_DK:         s = "da-DK"    '   &H406
    Case lcid_de_DE:         s = "de-DE"    '   &H407
    Case lcid_el_GR:         s = "el-GR"    '   &H408
    Case lcid_en_US:         s = "en-US"    '   &H409
    Case lcid_es_ES_tradnl:  s = "es-ES-tradnl"     '   &H40A
    Case lcid_FI_FI:         s = "FI-FI"    '   &H40B
    Case lcid_fr_fr:         s = "fr-fr"    '   &H40C
    Case lcid_he_IL:         s = "he-IL"    '   &H40D
    Case lcid_HU_HU:         s = "HU-HU"    '   &H40E
    Case lcid_is_IS:         s = "is-IS"    '   &H40F
    Case lcid_it_it:         s = "it-it"    '   &H410
    Case lcid_ja_JP:         s = "ja-JP"    '   &H411
    Case lcid_ko_kr:         s = "ko-kr"    '   &H412
    Case lcid_nl_nl:         s = "nl-nl"    '   &H413
    Case lcid_nb_NO:         s = "nb-NO"    '   &H414
    Case lcid_PL_PL:         s = "PL-PL"    '   &H415
    Case lcid_PT_br:         s = "PT-br"    '   &H416
    Case lcid_rm_CH:         s = "rm-CH"    '   &H417
    Case lcid_ro_ro:         s = "ro-ro"    '   &H418
    Case lcid_ru_ru:         s = "ru-ru"    '   &H419
    Case lcid_hr_hr:         s = "hr-hr"    '   &H41A
    Case lcid_SK_SK:         s = "SK-SK"    '   &H41B
    Case lcid_sq_AL:         s = "sq-AL"    '   &H41C
    Case lcid_SV_SE:         s = "SV-SE"    '   &H41D
    Case lcid_TH_TH:         s = "TH-TH"    '   &H41E
    Case lcid_TR_TR:         s = "TR-TR"    '   &H41F
    Case lcid_ur_PK:         s = "ur-PK"    '   &H420
    Case lcid_ID_ID:         s = "ID-ID"    '   &H421
    Case lcid_uk_UA:         s = "uk-UA"    '   &H422
    Case lcid_BE_By:         s = "BE-By"    '   &H423
    Case lcid_sl_si:         s = "sl-si"    '   &H424
    Case lcid_ET_EE:         s = "ET-EE"    '   &H425
    Case lcid_LV_LV:         s = "LV-LV"    '   &H426
    Case lcid_LT_LT:         s = "LT-LT"    '   &H427
    Case lcid_tg_Cyrl_TJ:    s = "tg-Cyrl-TJ"  '   &H428
    Case lcid_fa_IR:         s = "fa-IR"    '   &H429
    Case lcid_vi_VN:         s = "vi-VN"    '   &H42A
    Case lcid_hy_am:         s = "hy-am"    '   &H42B
    Case lcid_az_Latn_az:    s = "az-Latn-az" '   &H42C
    Case lcid_eu_es:         s = "eu-es"    '   &H42D
    Case lcid_hsb_de:        s = "hsb-de"       '   &H42E
    Case lcid_MK_MK:         s = "MK-MK"    '   &H42F
    Case lcid_st_ZA:         s = "st-ZA"    '   &H430
    Case lcid_ts_ZA:         s = "ts-ZA"    '   &H431
    Case lcid_TN_ZA:         s = "TN-ZA"    '   &H432
    Case lcid_VE_ZA:         s = "VE-ZA"    '   &H433
    Case lcid_xh_ZA:         s = "xh-ZA"    '   &H434
    Case lcid_zu_ZA:         s = "zu-ZA"    '   &H435
    Case lcid_AF_ZA:         s = "AF-ZA"    '   &H436
    Case lcid_ka_GE:         s = "ka-GE"    '   &H437
    '
    Case lcid_FO_FO:         s = "FO-FO"    '   &H438
    Case lcid_hi_IN:         s = "hi-IN"    '   &H439
    Case lcid_MT_MT:         s = "MT-MT"    '   &H43A
    Case lcid_SE_NO:         s = "SE-NO"    '   &H43B
    Case lcid_yi_1:          s = "yi-1"     '   &H43D
    Case lcid_ms_MY:         s = "ms-MY"    '   &H43E
    Case lcid_kk_KZ:         s = "kk-KZ"    '   &H43F
    Case lcid_ky_KG:         s = "ky-KG"    '   &H440
    Case lcid_sw_KE:         s = "sw-KE"    '   &H441
    Case lcid_tk_TM:         s = "tk-TM"    '   &H442
    Case lcid_uz_Latn_uz:    s = "uz-Latn-uz" '   &H443
    Case lcid_TT_ru:         s = "TT-ru"    '   &H444
    Case lcid_bn_IN:         s = "bn-IN"    '   &H445
    Case lcid_pa_IN:         s = "pa-IN"    '   &H446
    Case lcid_gu_IN:         s = "gu-IN"    '   &H447
    Case lcid_or_IN:         s = "or-IN"    '   &H448
    Case lcid_ta_IN:         s = "ta-IN"    '   &H449
    Case lcid_te_IN:         s = "te-IN"    '   &H44A
    Case lcid_kn_IN:         s = "kn-IN"    '   &H44B
    Case lcid_ml_IN:         s = "ml-IN"    '   &H44C
    Case lcid_as_IN:         s = "as-IN"    '   &H44D
    Case lcid_mr_IN:         s = "mr-IN"    '   &H44E
    Case lcid_sa_IN:         s = "sa-IN"    '   &H44F
    Case lcid_mn_mn:         s = "mn-mn"    '   &H450
    Case lcid_BO_CN:         s = "BO-CN"    '   &H451
    Case lcid_cy_GB:         s = "cy-GB"    '   &H452
    Case lcid_km_KH:         s = "km-KH"    '   &H453
    Case lcid_Lo_la:         s = "Lo-la"    '   &H454
    Case lcid_MY_MM:         s = "MY-MM"    '   &H455
    Case lcid_GL_es:         s = "GL-es"    '   &H456
    Case lcid_kok_IN:        s = "kok-IN"   '   &H457
    'Case lcid_mni_IN:        s = "mni-IN"   '   &H458  ', Reserved
    '
    'Case lcid_sd_Deva_IN:    s = "sd-Deva-IN" '   &H459  ', Reserved
    Case lcid_syr_SY:        s = "syr-SY"      '   &H45A
    Case lcid_si_LK:         s = "si-LK"    '   &H45B
    Case lcid_Chr_Cher_US:   s = "Chr-Cher-US"      '   &H45C
    Case lcid_iu_Cans_CA:    s = "iu-Cans-CA"       '   &H45D
    Case lcid_am_ET:         s = "am-ET"    '   &H45E
    Case lcid_tzm_Arab_MA:   s = "tzm-Arab-MA"      '   &H45F
    Case lcid_ks_Arab:       s = "ks-Arab"  '   &H460
    Case lcid_ne_NP:         s = "ne-NP"    '   &H461
    Case lcid_fy_nl:         s = "fy-nl"    '   &H462
    Case lcid_ps_AF:         s = "ps-AF"    '   &H463
    Case lcid_fil_PH:        s = "fil-PH"   '   &H464
    Case lcid_dv_MV:         s = "dv-MV"    '   &H465
    'Case lcid_bin_NG:        s = "bin-NG"   '   &H466  ', Reserved
    'Case lcid_ff_NG:         s = "ff-NG"    '   &H467  ', ff_Latn_NG
    Case lcid_ha_Latn_NG:    s = "ha-Latn-NG"       '   &H468
    'Case lcid_ibb_NG:        s = "ibb-NG"   '   &H469  ', Reserved
    Case lcid_yo_NG:         s = "yo-NG"    '   &H46A
    Case lcid_quz_BO:        s = "quz-BO"       '   &H46B
    Case lcid_nso_ZA:        s = "nso-ZA"       '   &H46C
    Case lcid_BA_ru:         s = "BA-ru"    '   &H46D
    Case lcid_lb_LU:         s = "lb-LU"    '   &H46E
    Case lcid_kl_GL:         s = "kl-GL"    '   &H46F
    Case lcid_ig_NG:         s = "ig-NG"    '   &H470
    Case lcid_kr_Latn_NG:    s = "kr-Latn-NG"       '   &H471
    Case lcid_OM_ET:         s = "OM-ET"    '   &H472
    Case lcid_ti_ET:         s = "ti-ET"    '   &H473
    Case lcid_gn_PY:         s = "gn-PY"    '   &H474
    Case lcid_haw_US:        s = "haw-US"       '   &H475
    Case lcid_la_VA:         s = "la-VA"    '   &H476
    Case lcid_SO_SO:         s = "SO-SO"    '   &H477
    Case lcid_ii_CN:         s = "ii-CN"    '   &H478
    '
    'Case lcid_pap_29:        s = "pap-29"   '   &H479  ', Reserved
    Case lcid_arn_CL:        s = "arn-CL"       '   &H47A
    Case lcid_moh_CA:        s = "moh-CA"       '   &H47C
    Case lcid_br_fr:         s = "br-fr"    '   &H47E
    Case lcid_ug_CN:         s = "ug-CN"    '   &H480
    Case lcid_mi_NZ:         s = "mi-NZ"    '   &H481
    Case lcid_oc_fr:         s = "oc-fr"    '   &H482
    Case lcid_CO_fr:         s = "CO-fr"    '   &H483
    Case lcid_gsw_fr:        s = "gsw-fr"       '   &H484
    Case lcid_sah_ru:        s = "sah-ru"       '   &H485
    'Case lcid_qut_GT:        s = "qut-GT"   '   &H486  ', Reserved
    Case lcid_RW_RW:         s = "RW-RW"    '   &H487
    Case lcid_wo_SN:         s = "wo-SN"    '   &H488
    Case lcid_prs_AF:        s = "prs-AF"       '   &H48C
    'Case lcid_plt_MG:        s = "plt-MG"   '   &H48D  ', Reserved
    'Case lcid_zh_yue_HK:     s = "zh-yue-HK"    '   &H48E  ', Reserved
    'Case lcid_tdd_Tale_CN:   s = "tdd-Tale-CN"  '   &H48F  ', Reserved
    'Case lcid_khb_Talu_CN:   s = "khb-Talu-CN"  '   &H490  ', Reserved
    Case lcid_gd_GB:         s = "gd-GB"    '   &H491
    Case lcid_ku_Arab_IQ:    s = "ku-Arab-IQ"       '   &H492
    'Case lcid_quc_CO:        s = "quc-CO"   '   &H493  ', Reserved
    Case lcid_qps_Ploc:      s = "qps-Ploc"     '   &H501
    Case lcid_qps_ploca:     s = "qps-ploca"    '   &H5FE
    Case lcid_ar_IQ:         s = "ar-IQ"    '   &H801
    Case lcid_CA_es_valencia: s = "CA-es-valencia"      '   &H803
    Case lcid_zh_CN:          s = "zh-CN"    '   &H804
    Case lcid_de_CH:          s = "de-CH"    '   &H807
    Case lcid_en_GB:          s = "en-GB"    '   &H809
    Case lcid_es_MX:          s = "es-MX"    '   &H80A
    Case lcid_fr_BE:          s = "fr-BE"    '   &H80C
    Case lcid_it_CH:          s = "it-CH"    '   &H810
    'Case lcid_ja_Ploc_JP:     s = "ja-Ploc-JP"   '   &H811  '
    '
    Case lcid_nl_BE:          s = "nl-BE"    '   &H813
    Case lcid_nn_NO:          s = "nn-NO"    '   &H814
    Case lcid_PT_PT:          s = "PT-PT"    '   &H816
    Case lcid_ro_MD:          s = "ro-MD"    '   &H818
    Case lcid_ru_MD:          s = "ru-MD"    '   &H819
    Case lcid_sr_Latn_CS:     s = "sr-Latn-CS"       '   &H81A
    Case lcid_SV_FI:          s = "SV-FI"    '   &H81D
    Case lcid_ur_IN:          s = "ur-IN"    '   &H820
    'Case 0x0827  Neither defined nor reserved   :    s =    "27  Neither defined nor reserved"  '
    'Case lcid_az_Cyrl_az:     s = "az-Cyrl-az"   '   &H82C  ', Reserved
    Case lcid_dsb_de:         s = "dsb-de"       '   &H82E
    Case lcid_TN_BW:          s = "TN-BW"    '   &H832
    Case lcid_SE_SE:          s = "SE-SE"    '   &H83B
    Case lcid_ga_IE:          s = "ga-IE"    '   &H83C
    Case lcid_ms_bn:          s = "ms-bn"    '   &H83E
    'Case lcid_kk_Latn_KZ:     s = "kk-Latn-KZ"   '   &H83F  ', Reserved
    'Case lcid_uz_Cyrl_uz:     s = "uz-Cyrl-uz"   '   &H843  ', Reserved
    Case lcid_bn_BD:          s = "bn-BD"    '   &H845
    Case lcid_pa_Arab_PK:     s = "pa-Arab-PK"       '   &H846
    Case lcid_ta_LK:          s = "ta-LK"    '   &H849
    'Case lcid_mn_Mong_CN:     s = "mn-Mong-CN"   '   &H850  ', Reserved
    'Case 'lcid_BO_BT:         s = "BO-BT"    '   &H851  ', Reserved
    Case lcid_sd_Arab_PK:     s = "sd-Arab-PK"       '   &H859
    Case lcid_iu_Latn_CA:     s = "iu-Latn-CA"       '   &H85D
    Case lcid_tzm_Latn_DZ:    s = "tzm-Latn-DZ"      '   &H85F
    Case lcid_ks_Deva_IN:     s = "ks-Deva-IN"       '   &H860
    Case lcid_ne_IN:          s = "ne-IN"    '   &H861
    Case lcid_ff_Latn_SN:     s = "ff-Latn-SN"       '   &H867
    Case lcid_quz_EC:         s = "quz-EC"       '   &H86B
    Case lcid_ti_ER:          s = "ti-ER"    '   &H873
    Case lcid_qps_plocm:      s = "qps-plocm"    '   &H9FF
    'Case 0x0C00  Locale without assigned LCID if the current user default locale. See section 2.2.1.    :    s =    "00  Locale without assigned LCID if the current user default locale. See section 2.2.1."   '
    '
    Case lcid_ar_EG:          s = "ar-EG"    '   &HC01
    Case lcid_zh_HK:          s = "zh-HK"    '   &HC04
    Case lcid_de_AT:          s = "de-AT"    '   &HC07
    Case lcid_en_AU:          s = "en-AU"    '   &HC09
    Case lcid_es_ES:          s = "es-ES"    '   &HC0A
    Case lcid_fr_CA:          s = "fr-CA"    '   &HC0C
    Case lcid_sr_Cyrl_CS:     s = "sr-Cyrl-CS"       '   &HC1A
    Case lcid_SE_FI:          s = "SE-FI"    '   &HC3B
    Case lcid_mn_Mong_mn:     s = "mn-Mong-mn"       '   &HC50
    Case lcid_DZ_BT:          s = "DZ-BT"    '   &HC51
    'Case lcid_tmz_MA:         s = "tmz-MA"   '   &HC5F  ', Reserved
    Case lcid_quz_PE:         s = "quz-PE"       '   &HC6B
    'Case 0x1000  Locale without assigned LCID if the current user default locale. See section 2.2.1.    :    s =    "00  Locale without assigned LCID if the current user default locale. See section 2.2.1."   '
    Case lcid_ar_LY:          s = "ar-LY"    '   &H1001
    Case lcid_zh_SG:          s = "zh-SG"    '   &H1004
    Case lcid_de_LU:          s = "de-LU"    '   &H1007
    Case lcid_en_CA:          s = "en-CA"    '   &H1009
    Case lcid_es_GT:          s = "es-GT"    '   &H100A
    Case lcid_fr_CH:          s = "fr-CH"    '   &H100C
    Case lcid_hr_BA:          s = "hr-BA"    '   &H101A
    Case lcid_smj_NO:         s = "smj-NO"       '   &H103B
    Case lcid_tzm_Tfng_MA:    s = "tzm-Tfng-MA"      '   &H105F
    Case lcid_ar_DZ:          s = "ar-DZ"    '   &H1401
    Case lcid_zh_MO:          s = "zh-MO"    '   &H1404
    Case lcid_de_LI:          s = "de-LI"    '   &H1407
    Case lcid_en_NZ:          s = "en-NZ"    '   &H1409
    Case lcid_es_CR:          s = "es-CR"    '   &H140A
    Case lcid_fr_LU:          s = "fr-LU"    '   &H140C
    Case lcid_bs_Latn_BA:     s = "bs-Latn-BA"       '   &H141A
    Case lcid_smj_SE:         s = "smj-SE"       '   &H143B
    Case lcid_ar_MA:          s = "ar-MA"    '   &H1801
    Case lcid_en_IE:          s = "en-IE"    '   &H1809
    '
    Case lcid_es_pa:          s = "es-pa"    '   &H180A
    Case lcid_fr_MC:          s = "fr-MC"    '   &H180C
    Case lcid_sr_Latn_BA:     s = "sr-Latn-BA"       '   &H181A
    Case lcid_sma_NO:         s = "sma-NO"       '   &H183B
    Case lcid_ar_TN:          s = "ar-TN"    '   &H1C01
    Case lcid_en_ZA:          s = "en-ZA"    '   &H1C09
    Case lcid_es_DO:          s = "es-DO"    '   &H1C0A
    Case lcid_fr_29:          s = "fr-29"    '   &H1C0C
    Case lcid_sr_Cyrl_BA:     s = "sr-Cyrl-BA"       '   &H1C1A
    Case lcid_sma_SE:         s = "sma-SE"       '   &H1C3B
    Case lcid_ar_OM:          s = "ar-OM"    '   &H2001
    'Case '0x2008  Neither defined nor reserved   :    s =    "08  Neither defined nor reserved"  '
    Case lcid_en_JM:          s = "en-JM"    '   &H2009
    Case lcid_es_VE:          s = "es-VE"    '   &H200A
    Case lcid_fr_RE:          s = "fr-RE"    '   &H200C
    Case lcid_bs_Cyrl_BA:     s = "bs-Cyrl-BA"       '   &H201A
    Case lcid_sms_FI:         s = "sms-FI"       '   &H203B
    Case lcid_ar_YE:          s = "ar-YE"    '   &H2401
    'Case lcid_en_29:          s = "en-29"    '   &H2409 ', Reserved
    Case lcid_es_CO:          s = "es-CO"    '   &H240A
    Case lcid_fr_CD:          s = "fr-CD"    '   &H240C
    Case lcid_sr_Latn_RS:     s = "sr-Latn-RS"       '   &H241A
    Case lcid_smn_FI:         s = "smn-FI"       '   &H243B
    Case lcid_ar_SY:          s = "ar-SY"    '   &H2801
    Case lcid_en_BZ:          s = "en-BZ"    '   &H2809
    Case lcid_es_PE:          s = "es-PE"    '   &H280A
    Case lcid_fr_SN:          s = "fr-SN"    '   &H280C
    Case lcid_sr_Cyrl_RS:     s = "sr-Cyrl-RS"       '   &H281A
    Case lcid_ar_JO:          s = "ar-JO"    '   &H2C01
    Case lcid_en_TT:          s = "en-TT"    '   &H2C09
    Case lcid_es_ar:          s = "es-ar"    '   &H2C0A
    Case lcid_fr_CM:          s = "fr-CM"    '   &H2C0C
    '
    Case lcid_sr_Latn_Me:     s = "sr-Latn-Me"       '   &H2C1A
    'Case '0x3000  Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x3000. See section 2.2.1."    '
    Case lcid_ar_lb:          s = "ar-lb"    '   &H3001
    Case lcid_en_ZW:          s = "en-ZW"    '   &H3009
    Case lcid_es_EC:          s = "es-EC"    '   &H300A
    Case lcid_fr_ci:          s = "fr-ci"    '   &H300C
    Case lcid_sr_Cyrl_Me:     s = "sr-Cyrl-Me"       '   &H301A
    'Case '0x3400  Unassigned LCID locale temporarily assigned to LCID 0x3400. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x3400. See section 2.2.1."    '
    Case lcid_ar_KW:          s = "ar-KW"    '   &H3401
    Case lcid_en_PH:          s = "en-PH"    '   &H3409
    Case lcid_es_CL:          s = "es-CL"    '   &H340A
    Case lcid_fr_ML:          s = "fr-ML"    '   &H340C
    'Case '0x3800  Unassigned LCID locale temporarily assigned to LCID 0x3800. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x3800. See section 2.2.1."    '
    Case lcid_ar_AE:          s = "ar-AE"    '   &H3801
    'Case lcid_en_ID:         s = "en-ID"    '   &H3809 ', Reserved
    Case lcid_es_UY:          s = "es-UY"    '   &H380A
    Case lcid_fr_MA:          s = "fr-MA"    '   &H380C
    'Case '0x3C00  Unassigned LCID locale temporarily assigned to LCID 0x3C00. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x3C00. See section 2.2.1."    '
    Case lcid_ar_BH:          s = "ar-BH"    '   &H3C01
    Case lcid_en_HK:          s = "en-HK"    '   &H3C09
    Case lcid_es_PY:          s = "es-PY"    '   &H3C0A
    Case lcid_fr_HT:          s = "fr-HT"    '   &H3C0C
    'Case '0x4000  Unassigned LCID locale temporarily assigned to LCID 0x4000. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x4000. See section 2.2.1."    '
    Case lcid_ar_QA:          s = "ar-QA"    '   &H4001
    Case lcid_en_IN:          s = "en-IN"    '   &H4009
    Case lcid_es_BO:          s = "es-BO"    '   &H400A
    'Case '0x4400  Unassigned LCID locale temporarily assigned to LCID 0x4400. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x4400. See section 2.2.1."    '
    'Case lcid_ar_Ploc_sa:     s = "_ar_Ploc_sa"   '   &H4401 ', Reserved
    Case lcid_en_MY:          s = "en-MY"    '   &H4409
    Case lcid_es_SV:          s = "es-SV"    '   &H440A
    'Case '0x4800  Unassigned LCID locale temporarily assigned to LCID 0x4800. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x4800. See section 2.2.1."    '
    'Case lcid_ar_145:         s = "_ar_145"   '   &H4801 ', Reserved
    '
    Case lcid_en_SG:          s = "en-SG"    '   &H4809
    Case lcid_es_HN:          s = "es-HN"    '   &H480A
    'Case '0x4C00  Unassigned LCID locale temporarily assigned to LCID 0x4C00. See section 2.2.1. :    s =    "00  Unassigned LCID locale temporarily assigned to LCID 0x4C00. See section 2.2.1."    '
    Case lcid_en_AE:          s = "en-AE"    '   &H4C09
    Case lcid_es_NI:          s = "es-NI"    '   &H4C0A
    'Case lcid_en_BH:          s = "en-BH"    '   &H5009 ', Reserved
    Case lcid_es_PR:          s = "es-PR"    '   &H500A
    'Case lcid_en_EG:          s = "en-EG"    '   &H5409 ', Reserved
    Case lcid_es_US:          s = "es-US"    '   &H540A
    'Case lcid_en_JO:          s = "en-JO"    '   &H5809 ', Reserved
    'Case lcid_es_419:         s = "es-419"   '   &H580A ', Reserved
    'Case lcid_en_KW:          s = "en-KW"    '   &H5C09 ', Reserved
    Case lcid_es_CU:          s = "es-CU"    '   &H5C0A
    'Case lcid_en_TR:          s = "en-TR"    '   &H6009 ', Reserved
    'Case lcid_en_YE:          s = "en-YE"    '   &H6409 ', Reserved
    Case lcid_bs_Cyrl:        s = "bs-Cyrl"      '   &H641A
    Case lcid_bs_Latn:        s = "bs-Latn"      '   &H681A
    Case lcid_sr_Cyrl:        s = "sr-Cyrl"      '   &H6C1A
    Case lcid_sr_Latn:        s = "sr-Latn"      '   &H701A
    Case lcid_smn:            s = "smn"      '   &H703B
    Case lcid_az_Cyrl:        s = "az-Cyrl"      '   &H742C
    Case lcid_sms:            s = "sms"      '   &H743B
    Case lcid_zh:             s = "zh"       '   &H7804
    Case lcid_nn:             s = "nn"       '   &H7814
    Case lcid_bs:             s = "bs"       '   &H781A
    Case lcid_az_Latn:        s = "az-Latn"      '   &H782C
    Case lcid_sma:            s = "sma"      '   &H783B
    'Case lcid_kk_Cyrl:        s = "_kk_Cyrl"  '   &H783F ', Reserved
    Case lcid_uz_Cyrl:        s = "uz-Cyrl"      '   &H7843
    Case lcid_mn_Cyrl:        s = "mn-Cyrl"      '   &H7850
    Case lcid_iu_Cans:        s = "iu-Cans"      '   &H785D
    Case lcid_tzm_Tfng:       s = "tzm-Tfng"     '   &H785F
    '
    Case lcid_zh_Hant:        s = "zh-Hant"      '   &H7C04
    Case lcid_nb:             s = "nb"       '   &H7C14
    Case lcid_sr:             s = "sr"       '   &H7C1A
    Case lcid_tg_Cyrl:        s = "tg-Cyrl"      '   &H7C28
    Case lcid_dsb:            s = "dsb"      '   &H7C2E
    Case lcid_smj:            s = "smj"      '   &H7C3B
    'Case lcid_kk_Latn:        s = "kk-Latn"  '   &H7C3F  ', Reserved
    Case lcid_uz_Latn:        s = "uz-Latn"      '   &H7C43
    Case lcid_pa_Arab:        s = "pa-Arab"      '   &H7C46
    Case lcid_mn_Mong:        s = "mn-Mong"      '   &H7C50
    Case lcid_sd_Arab:        s = "sd-Arab"      '   &H7C59
    Case lcid_Chr_Cher:       s = "Chr-Cher"     '   &H7C5C
    Case lcid_iu_Latn:        s = "iu-Latn"      '   &H7C5D
    Case lcid_tzm_Latn:       s = "tzm-Latn"     '   &H7C5F
    Case lcid_ff_Latn:        s = "ff-Latn"      '   &H7C67
    Case lcid_ha_Latn:        s = "ha-Latn"      '   &H7C68
    Case lcid_ku_Arab:        s = "ku-Arab"      '   &H7C92
    'Case 0xF2EE_Reserved:     s = "EE Reserved"   '
    'Case lcid_fr_15:          s = "_fr_15"    '   &HE40C ', Reserved
    'Case 0xEEEE_Reserved:     s = "EE_Reserved"
    End Select
    ELCID_ToStr = s
End Function

Public Function ELCID_Parse(s As String) As ELCID
    Dim e As ELCID
    Select Case s
    Case "ar":      e = ELCID.lcid_ar
    Case "BG":      e = ELCID.lcid_BG
    Case "CA":      e = ELCID.lcid_CA
    Case "zh-Hans": e = ELCID.lcid_zh_Hans
    Case "CS":      e = ELCID.lcid_CS
    Case "da":      e = ELCID.lcid_da
    Case "de":      e = ELCID.lcid_de
    Case "el":      e = ELCID.lcid_el
    Case "en":      e = ELCID.lcid_en
    Case "es":      e = ELCID.lcid_es
    Case "FI":      e = ELCID.lcid_FI
    Case "fr":      e = ELCID.lcid_fr
    Case "he":      e = ELCID.lcid_he
    Case "HU":      e = ELCID.lcid_HU
    Case "is":      e = ELCID.lcid_is_
    Case "it":      e = ELCID.lcid_it
    Case "ja":      e = ELCID.lcid_ja
    Case "ko":      e = ELCID.lcid_ko
    Case "nl":      e = ELCID.lcid_nl
    Case "NO":      e = ELCID.lcid_NO
    Case "PL":      e = ELCID.lcid_PL
    Case "PT":      e = ELCID.lcid_PT
    Case "rm":      e = ELCID.lcid_rm
    Case "ro":      e = ELCID.lcid_ro
    Case "ru":      e = ELCID.lcid_ru
    Case "hr":      e = ELCID.lcid_hr
    Case "SK":      e = ELCID.lcid_SK
    Case "sq":      e = ELCID.lcid_sq
    Case "SV":      e = ELCID.lcid_SV
    Case "TH":      e = ELCID.lcid_TH
    Case "TR":      e = ELCID.lcid_TR
    Case "ur":      e = ELCID.lcid_ur
    Case "ID":      e = ELCID.lcid_ID
    Case "uk":      e = ELCID.lcid_uk
    Case "BE":      e = ELCID.lcid_BE
    Case "sl":      e = ELCID.lcid_sl
    Case "ET":      e = ELCID.lcid_ET
    Case "LV":      e = ELCID.lcid_LV
    Case "LT":      e = ELCID.lcid_LT
    Case "tg":      e = ELCID.lcid_tg
    Case "fa":      e = ELCID.lcid_fa
    Case "vi":      e = ELCID.lcid_vi
    Case "hy":      e = ELCID.lcid_hy
    Case "az":      e = ELCID.lcid_az
    Case "eu":      e = ELCID.lcid_eu
    Case "hsb":     e = ELCID.lcid_hsb
    Case "MK":      e = ELCID.lcid_MK
    Case "st":      e = ELCID.lcid_st
    Case "ts":      e = ELCID.lcid_ts
    Case "TN":      e = ELCID.lcid_TN
    Case "VE":      e = ELCID.lcid_VE
    Case "xh":      e = ELCID.lcid_xh
    Case "zu":      e = ELCID.lcid_zu
    Case "AF":      e = ELCID.lcid_AF
    Case "ka":      e = ELCID.lcid_ka
    Case "FO":      e = ELCID.lcid_FO
    Case "Hi":      e = ELCID.lcid_Hi
    Case "MT":      e = ELCID.lcid_MT
    Case "SE":      e = ELCID.lcid_SE
    Case "ga":      e = ELCID.lcid_ga
    'Case "yi":      e = ELCID.lcid_yi
    Case "ms":      e = ELCID.lcid_ms
    Case "kk":      e = ELCID.lcid_kk
    Case "ky":      e = ELCID.lcid_ky
    Case "sw":      e = ELCID.lcid_sw
    Case "tk":      e = ELCID.lcid_tk
    Case "uz":      e = ELCID.lcid_uz
    Case "TT":      e = ELCID.lcid_TT
    Case "bn":      e = ELCID.lcid_bn
    Case "pa":      e = ELCID.lcid_pa
    Case "gu":      e = ELCID.lcid_gu
    Case "or":      e = ELCID.lcid_or_
    Case "ta":      e = ELCID.lcid_ta
    Case "te":      e = ELCID.lcid_te
    'Case    #WERT!
    Case "kn":      e = ELCID.lcid_kn
    Case "ML":      e = ELCID.lcid_ML
    Case "as":      e = ELCID.lcid_as_
    Case "mr":      e = ELCID.lcid_mr
    Case "sa":      e = ELCID.lcid_sa
    Case "mn":      e = ELCID.lcid_mn
    Case "BO":      e = ELCID.lcid_BO
    Case "cy":      e = ELCID.lcid_cy
    Case "km":      e = ELCID.lcid_km
    Case "Lo":      e = ELCID.lcid_Lo
    Case "MY":      e = ELCID.lcid_MY
    Case "GL":      e = ELCID.lcid_GL
    Case "kok":     e = ELCID.lcid_kok
    'Case "mni":     e = ELCID.lcid_mni
    Case "sd":      e = ELCID.lcid_sd
    Case "syr":     e = ELCID.lcid_syr
    Case "si":      e = ELCID.lcid_si
    Case "Chr":     e = ELCID.lcid_Chr
    Case "iu":      e = ELCID.lcid_iu
    Case "am":      e = ELCID.lcid_am
    Case "tzm":     e = ELCID.lcid_tzm
    Case "ks":      e = ELCID.lcid_ks
    Case "ne":      e = ELCID.lcid_ne
    Case "fy":      e = ELCID.lcid_fy
    Case "ps":      e = ELCID.lcid_ps
    Case "fil":     e = ELCID.lcid_fil
    Case "dv":      e = ELCID.lcid_dv
    'Case "bin":     e = ELCID.lcid_bin
    Case "ff":      e = ELCID.lcid_ff
    Case "ha":      e = ELCID.lcid_ha
    'Case "ibb":     e = ELCID.lcid_ibb
    Case "yo":      e = ELCID.lcid_yo
    'Case    #WERT!
    Case "quz":     e = ELCID.lcid_quz
    Case "nso":     e = ELCID.lcid_nso
    Case "BA":      e = ELCID.lcid_BA
    Case "lb":      e = ELCID.lcid_lb
    Case "kl":      e = ELCID.lcid_kl
    Case "ig":      e = ELCID.lcid_ig
    'Case "kr":      e = ELCID.lcid_kr
    Case "OM":      e = ELCID.lcid_OM
    Case "ti":      e = ELCID.lcid_ti
    Case "gn":      e = ELCID.lcid_gn
    Case "haw":     e = ELCID.lcid_haw
    'Case "la":      e = ELCID.lcid_la
    'Case "SO":      e = ELCID.lcid_SO
    Case "ii":      e = ELCID.lcid_ii
    'Case "pap":     e = ELCID.lcid_pap
    Case "arn":     e = ELCID.lcid_arn
    'Case    #WERT!
    Case "moh":     e = ELCID.lcid_moh
    'Case    #WERT!
    Case "br":      e = ELCID.lcid_br
    'Case    #WERT!
    Case "ug":      e = ELCID.lcid_ug
    Case "mi":      e = ELCID.lcid_mi
    Case "oc":      e = ELCID.lcid_oc
    Case "CO":      e = ELCID.lcid_CO
    Case "gsw":     e = ELCID.lcid_gsw
    Case "sah":     e = ELCID.lcid_sah
    Case "qut":     e = ELCID.lcid_qut
    Case "RW":      e = ELCID.lcid_RW
    Case "wo":      e = ELCID.lcid_wo
    'Case    #WERT!
    'Case    #WERT!
    'Case    #WERT!
    'Case    #WERT!
    Case "prs":     e = ELCID.lcid_prs
    'Case    #WERT!
    'Case    #WERT!
    'Case    #WERT!
    'Case    #WERT!
    Case "gd":      e = ELCID.lcid_gd
    Case "ku":      e = ELCID.lcid_ku
    'Case "quc":     e = ELCID.lcid_quc
    Case "ar-sa":   e = ELCID.lcid_ar_sa
    Case "BG-BG":   e = ELCID.lcid_BG_BG
    Case "CA-es":   e = ELCID.lcid_CA_es
    Case "zh-TW":   e = ELCID.lcid_zh_TW
    Case "CS-CZ":   e = ELCID.lcid_CS_CZ
    Case "da-DK":   e = ELCID.lcid_da_DK
    Case "de-DE":   e = ELCID.lcid_de_DE
    Case "el-GR":   e = ELCID.lcid_el_GR
    Case "en-US":   e = ELCID.lcid_en_US
    Case "es-ES-tradnl": e = ELCID.lcid_es_ES_tradnl
    Case "FI-FI":   e = ELCID.lcid_FI_FI
    Case "fr-fr":   e = ELCID.lcid_fr_fr
    Case "he-IL":   e = ELCID.lcid_he_IL
    Case "HU-HU":   e = ELCID.lcid_HU_HU
    Case "is-IS":   e = ELCID.lcid_is_IS
    Case "it-it":   e = ELCID.lcid_it_it
    Case "ja-JP":   e = ELCID.lcid_ja_JP
    Case "ko-kr":   e = ELCID.lcid_ko_kr
    Case "nl-nl":   e = ELCID.lcid_nl_nl
    Case "nb-NO":   e = ELCID.lcid_nb_NO
    Case "PL-PL":   e = ELCID.lcid_PL_PL
    Case "PT-br":   e = ELCID.lcid_PT_br
    Case "rm-CH":   e = ELCID.lcid_rm_CH
    Case "ro-ro":   e = ELCID.lcid_ro_ro
    Case "ru-ru":   e = ELCID.lcid_ru_ru
    Case "hr-hr":   e = ELCID.lcid_hr_hr
    Case "SK-SK":   e = ELCID.lcid_SK_SK
    Case "sq-AL":   e = ELCID.lcid_sq_AL
    Case "SV-SE":   e = ELCID.lcid_SV_SE
    Case "TH-TH":   e = ELCID.lcid_TH_TH
    Case "TR-TR":   e = ELCID.lcid_TR_TR
    Case "ur-PK":   e = ELCID.lcid_ur_PK
    Case "ID-ID":   e = ELCID.lcid_ID_ID
    Case "uk-UA":   e = ELCID.lcid_uk_UA
    Case "BE-By":   e = ELCID.lcid_BE_By
    Case "sl-si":   e = ELCID.lcid_sl_si
    Case "ET-EE":   e = ELCID.lcid_ET_EE
    Case "LV-LV":   e = ELCID.lcid_LV_LV
    Case "LT-LT":   e = ELCID.lcid_LT_LT
    Case "tg-Cyrl-TJ": e = ELCID.lcid_tg_Cyrl_TJ
    Case "fa-IR":   e = ELCID.lcid_fa_IR
    Case "vi-VN":   e = ELCID.lcid_vi_VN
    Case "hy-am":   e = ELCID.lcid_hy_am
    Case "az-Latn-az": e = ELCID.lcid_az_Latn_az
    Case "eu-es":   e = ELCID.lcid_eu_es
    Case "hsb-de":  e = ELCID.lcid_hsb_de
    Case "MK-MK":   e = ELCID.lcid_MK_MK
    Case "st-ZA":   e = ELCID.lcid_st_ZA
    Case "ts-ZA":   e = ELCID.lcid_ts_ZA
    Case "TN-ZA":   e = ELCID.lcid_TN_ZA
    Case "VE-ZA":   e = ELCID.lcid_VE_ZA
    Case "xh-ZA":   e = ELCID.lcid_xh_ZA
    Case "zu-ZA":   e = ELCID.lcid_zu_ZA
    Case "AF-ZA":   e = ELCID.lcid_AF_ZA
    Case "ka-GE":   e = ELCID.lcid_ka_GE
    'Case    #WERT!
    Case "FO-FO":   e = ELCID.lcid_FO_FO
    Case "hi-IN":   e = ELCID.lcid_hi_IN
    Case "MT-MT":   e = ELCID.lcid_MT_MT
    Case "SE-NO":   e = ELCID.lcid_SE_NO
    Case "yi-1":    e = ELCID.lcid_yi_1
    Case "ms-MY":   e = ELCID.lcid_ms_MY
    Case "kk-KZ":   e = ELCID.lcid_kk_KZ
    Case "ky-KG":   e = ELCID.lcid_ky_KG
    Case "sw-KE":   e = ELCID.lcid_sw_KE
    Case "tk-TM":   e = ELCID.lcid_tk_TM
    Case "uz-Latn-uz": e = ELCID.lcid_uz_Latn_uz
    Case "TT-ru":   e = ELCID.lcid_TT_ru
    Case "bn-IN":   e = ELCID.lcid_bn_IN
    Case "pa-IN":   e = ELCID.lcid_pa_IN
    Case "gu-IN":   e = ELCID.lcid_gu_IN
    Case "or-IN":   e = ELCID.lcid_or_IN
    Case "ta-IN":   e = ELCID.lcid_ta_IN
    Case "te-IN":   e = ELCID.lcid_te_IN
    Case "kn-IN":   e = ELCID.lcid_kn_IN
    Case "ml-IN":   e = ELCID.lcid_ml_IN
    Case "as-IN":   e = ELCID.lcid_as_IN
    Case "mr-IN":   e = ELCID.lcid_mr_IN
    Case "sa-IN":   e = ELCID.lcid_sa_IN
    Case "mn-mn":   e = ELCID.lcid_mn_mn
    Case "BO-CN":   e = ELCID.lcid_BO_CN
    Case "cy-GB":   e = ELCID.lcid_cy_GB
    Case "km-KH":   e = ELCID.lcid_km_KH
    Case "Lo-la":   e = ELCID.lcid_Lo_la
    Case "MY-MM":   e = ELCID.lcid_MY_MM
    Case "GL-es":   e = ELCID.lcid_GL_es
    Case "kok-IN":  e = ELCID.lcid_kok_IN
    'Case "mni_IN":  e = ELCID.lcid_mni_IN
    'Case    #WERT!
    'Case "sd_Deva_IN": e = ELCID.lcid_sd_Deva_IN
    Case "syr-SY":  e = ELCID.lcid_syr_SY
    Case "si-LK":   e = ELCID.lcid_si_LK
    Case "Chr-Cher-US": e = ELCID.lcid_Chr_Cher_US
    Case "iu-Cans-CA": e = ELCID.lcid_iu_Cans_CA
    Case "am-ET":   e = ELCID.lcid_am_ET
    Case "tzm-Arab-MA": e = ELCID.lcid_tzm_Arab_MA
    Case "ks-Arab": e = ELCID.lcid_ks_Arab
    Case "ne-NP":   e = ELCID.lcid_ne_NP
    Case "fy-nl":   e = ELCID.lcid_fy_nl
    Case "ps-AF":   e = ELCID.lcid_ps_AF
    Case "fil-PH":  e = ELCID.lcid_fil_PH
    Case "dv-MV":   e = ELCID.lcid_dv_MV
    'Case "bin_NG":  e = ELCID.'lcid_bin_NG
    'Case    "_ff_NG" : e = ELCID.'lcid_ff_NG
    Case "ha-Latn-NG": e = ELCID.lcid_ha_Latn_NG
    'Case    "_ibb_NG" : e = ELCID.'lcid_ibb_NG
    Case "yo-NG":   e = ELCID.lcid_yo_NG
    Case "quz-BO":  e = ELCID.lcid_quz_BO
    Case "nso-ZA":  e = ELCID.lcid_nso_ZA
    Case "BA-ru":   e = ELCID.lcid_BA_ru
    Case "lb-LU":   e = ELCID.lcid_lb_LU
    Case "kl-GL":   e = ELCID.lcid_kl_GL
    Case "ig-NG":   e = ELCID.lcid_ig_NG
    Case "kr-Latn-NG": e = ELCID.lcid_kr_Latn_NG
    Case "OM-ET":   e = ELCID.lcid_OM_ET
    Case "ti-ET":   e = ELCID.lcid_ti_ET
    Case "gn-PY":   e = ELCID.lcid_gn_PY
    Case "haw-US": e = ELCID.lcid_haw_US
    Case "la-VA": e = ELCID.lcid_la_VA
    Case "SO-SO": e = ELCID.lcid_SO_SO
    Case "ii-CN": e = ELCID.lcid_ii_CN
    'Case    #WERT!
    'Case    "_pap_29" : e = ELCID.'lcid_pap_29
    Case "arn-CL": e = ELCID.lcid_arn_CL
    Case "moh-CA": e = ELCID.lcid_moh_CA
    Case "br-fr": e = ELCID.lcid_br_fr
    Case "ug-CN": e = ELCID.lcid_ug_CN
    Case "mi-NZ": e = ELCID.lcid_mi_NZ
    Case "oc-fr": e = ELCID.lcid_oc_fr
    Case "CO-fr": e = ELCID.lcid_CO_fr
    Case "gsw-fr": e = ELCID.lcid_gsw_fr
    Case "sah-ru": e = ELCID.lcid_sah_ru
    'Case    "_qut_GT" : e = ELCID.'lcid_qut_GT
    Case "RW-RW": e = ELCID.lcid_RW_RW
    Case "wo-SN": e = ELCID.lcid_wo_SN
    Case "prs-AF": e = ELCID.lcid_prs_AF
    'Case    "_plt_MG" : e = ELCID.'lcid_plt_MG
    'Case    "_zh_yue_HK" : e = ELCID.'lcid_zh_yue_HK
    'Case    "_tdd_Tale_CN" : e = ELCID.'lcid_tdd_Tale_CN
    'Case    "_khb_Talu_CN" : e = ELCID.'lcid_khb_Talu_CN
    Case "gd-GB": e = ELCID.lcid_gd_GB
    Case "ku-Arab-IQ": e = ELCID.lcid_ku_Arab_IQ
    'Case    "_quc_CO" : e = ELCID.'lcid_quc_CO
    Case "qps-Ploc": e = ELCID.lcid_qps_Ploc
    Case "qps-ploca": e = ELCID.lcid_qps_ploca
    Case "ar-IQ": e = ELCID.lcid_ar_IQ
    Case "CA-es-valencia": e = ELCID.lcid_CA_es_valencia
    Case "zh-CN": e = ELCID.lcid_zh_CN
    Case "de-CH": e = ELCID.lcid_de_CH
    Case "en-GB": e = ELCID.lcid_en_GB
    Case "es-MX": e = ELCID.lcid_es_MX
    Case "fr-BE": e = ELCID.lcid_fr_BE
    Case "it-CH": e = ELCID.lcid_it_CH
    'Case    "_ja_Ploc_JP" : e = ELCID.'lcid_ja_Ploc_JP
    'Case    #WERT!
    Case "nl-BE": e = ELCID.lcid_nl_BE
    Case "nn-NO": e = ELCID.lcid_nn_NO
    Case "PT-PT": e = ELCID.lcid_PT_PT
    Case "ro-MD": e = ELCID.lcid_ro_MD
    Case "ru-MD": e = ELCID.lcid_ru_MD
    Case "sr-Latn-CS": e = ELCID.lcid_sr_Latn_CS
    Case "SV-FI": e = ELCID.lcid_SV_FI
    Case "ur-IN": e = ELCID.lcid_ur_IN
    'Case    #WERT!
    'Case    "_az_Cyrl_az" : e = ELCID.'lcid_az_Cyrl_az
    Case "dsb-de": e = ELCID.lcid_dsb_de
    Case "TN-BW": e = ELCID.lcid_TN_BW
    Case "SE-SE": e = ELCID.lcid_SE_SE
    Case "ga-IE": e = ELCID.lcid_ga_IE
    Case "ms-bn": e = ELCID.lcid_ms_bn
    'Case    "_kk_Latn_KZ" : e = ELCID.'lcid_kk_Latn_KZ
    'Case    "_uz_Cyrl_uz" : e = ELCID.'lcid_uz_Cyrl_uz
    Case "bn-BD": e = ELCID.lcid_bn_BD
    Case "pa-Arab-PK": e = ELCID.lcid_pa_Arab_PK
    Case "ta-LK": e = ELCID.lcid_ta_LK
    'Case    "_mn_Mong_CN" : e = ELCID.'lcid_mn_Mong_CN
    'Case    "_BO_BT" : e = ELCID.'lcid_BO_BT
    Case "sd-Arab-PK": e = ELCID.lcid_sd_Arab_PK
    Case "iu-Latn-CA": e = ELCID.lcid_iu_Latn_CA
    Case "tzm-Latn-DZ": e = ELCID.lcid_tzm_Latn_DZ
    Case "ks-Deva-IN": e = ELCID.lcid_ks_Deva_IN
    Case "ne-IN": e = ELCID.lcid_ne_IN
    Case "ff-Latn-SN": e = ELCID.lcid_ff_Latn_SN
    Case "quz-EC": e = ELCID.lcid_quz_EC
    Case "ti-ER": e = ELCID.lcid_ti_ER
    Case "qps-plocm": e = ELCID.lcid_qps_plocm
    'Case    #WERT!
    'Case    #WERT!
    Case "ar-EG": e = ELCID.lcid_ar_EG
    Case "zh-HK": e = ELCID.lcid_zh_HK
    Case "de-AT": e = ELCID.lcid_de_AT
    Case "en-AU": e = ELCID.lcid_en_AU
    Case "es-ES": e = ELCID.lcid_es_ES
    Case "fr-CA": e = ELCID.lcid_fr_CA
    Case "sr-Cyrl-CS": e = ELCID.lcid_sr_Cyrl_CS
    Case "SE-FI": e = ELCID.lcid_SE_FI
    Case "mn-Mong-mn": e = ELCID.lcid_mn_Mong_mn
    Case "DZ-BT": e = ELCID.lcid_DZ_BT
    'Case    "_tmz_MA" : e = ELCID.'lcid_tmz_MA
    Case "quz-PE": e = ELCID.lcid_quz_PE
    'Case    #WERT!
    Case "ar-LY": e = ELCID.lcid_ar_LY
    Case "zh-SG": e = ELCID.lcid_zh_SG
    Case "de-LU": e = ELCID.lcid_de_LU
    Case "en-CA": e = ELCID.lcid_en_CA
    Case "es-GT": e = ELCID.lcid_es_GT
    Case "fr-CH": e = ELCID.lcid_fr_CH
    Case "hr-BA": e = ELCID.lcid_hr_BA
    Case "smj-NO": e = ELCID.lcid_smj_NO
    Case "tzm-Tfng-MA": e = ELCID.lcid_tzm_Tfng_MA
    Case "ar-DZ": e = ELCID.lcid_ar_DZ
    Case "zh-MO": e = ELCID.lcid_zh_MO
    Case "de-LI": e = ELCID.lcid_de_LI
    Case "en-NZ": e = ELCID.lcid_en_NZ
    Case "es-CR": e = ELCID.lcid_es_CR
    Case "fr-LU": e = ELCID.lcid_fr_LU
    Case "bs-Latn-BA": e = ELCID.lcid_bs_Latn_BA
    Case "smj-SE": e = ELCID.lcid_smj_SE
    Case "ar-MA": e = ELCID.lcid_ar_MA
    Case "en-IE": e = ELCID.lcid_en_IE
    'Case    #WERT!
    Case "es-pa": e = ELCID.lcid_es_pa
    Case "fr-MC": e = ELCID.lcid_fr_MC
    Case "sr-Latn-BA": e = ELCID.lcid_sr_Latn_BA
    Case "sma-NO": e = ELCID.lcid_sma_NO
    Case "ar-TN": e = ELCID.lcid_ar_TN
    Case "en-ZA": e = ELCID.lcid_en_ZA
    Case "es-DO": e = ELCID.lcid_es_DO
    Case "fr-29": e = ELCID.lcid_fr_29
    Case "sr-Cyrl-BA": e = ELCID.lcid_sr_Cyrl_BA
    Case "sma-SE": e = ELCID.lcid_sma_SE
    Case "ar-OM": e = ELCID.lcid_ar_OM
    'Case    #WERT!
    Case "en-JM": e = ELCID.lcid_en_JM
    Case "es-VE": e = ELCID.lcid_es_VE
    Case "fr-RE": e = ELCID.lcid_fr_RE
    Case "bs-Cyrl-BA": e = ELCID.lcid_bs_Cyrl_BA
    Case "sms-FI": e = ELCID.lcid_sms_FI
    Case "ar-YE": e = ELCID.lcid_ar_YE
    'Case    "_en_29" : e = ELCID.'lcid_en_29
    Case "es-CO": e = ELCID.lcid_es_CO
    Case "fr-CD": e = ELCID.lcid_fr_CD
    Case "sr-Latn-RS": e = ELCID.lcid_sr_Latn_RS
    Case "smn-FI": e = ELCID.lcid_smn_FI
    Case "ar-SY": e = ELCID.lcid_ar_SY
    Case "en-BZ": e = ELCID.lcid_en_BZ
    Case "es-PE": e = ELCID.lcid_es_PE
    Case "fr-SN": e = ELCID.lcid_fr_SN
    Case "sr-Cyrl-RS": e = ELCID.lcid_sr_Cyrl_RS
    Case "ar-JO": e = ELCID.lcid_ar_JO
    Case "en-TT": e = ELCID.lcid_en_TT
    Case "es-ar": e = ELCID.lcid_es_ar
    Case "fr-CM": e = ELCID.lcid_fr_CM
    'Case    #WERT!
    Case "sr-Latn-Me": e = ELCID.lcid_sr_Latn_Me
    'Case    #WERT!
    Case "ar-lb": e = ELCID.lcid_ar_lb
    Case "en-ZW": e = ELCID.lcid_en_ZW
    Case "es-EC": e = ELCID.lcid_es_EC
    Case "fr-ci": e = ELCID.lcid_fr_ci
    Case "sr-Cyrl-Me": e = ELCID.lcid_sr_Cyrl_Me
    'Case    #WERT!
    Case "ar-KW": e = ELCID.lcid_ar_KW
    Case "en-PH": e = ELCID.lcid_en_PH
    Case "es-CL": e = ELCID.lcid_es_CL
    Case "fr-ML": e = ELCID.lcid_fr_ML
    'Case    #WERT!
    Case "ar-AE": e = ELCID.lcid_ar_AE
    'Case    "_en_ID" : e = ELCID.'lcid_en_ID
    Case "es-UY": e = ELCID.lcid_es_UY
    Case "fr-MA": e = ELCID.lcid_fr_MA
    'Case    #WERT!
    Case "ar-BH": e = ELCID.lcid_ar_BH
    Case "en-HK": e = ELCID.lcid_en_HK
    Case "es-PY": e = ELCID.lcid_es_PY
    Case "fr-HT": e = ELCID.lcid_fr_HT
    'Case    #WERT!
    Case "ar-QA": e = ELCID.lcid_ar_QA
    Case "en-IN": e = ELCID.lcid_en_IN
    Case "es-BO": e = ELCID.lcid_es_BO
    'Case    #WERT!
    'Case    "_ar_Ploc_sa" : e = ELCID.'lcid_ar_Ploc_sa
    Case "en-MY": e = ELCID.lcid_en_MY
    Case "es-SV": e = ELCID.lcid_es_SV
    'Case    #WERT!
    'Case    "_ar_145" : e = ELCID.'lcid_ar_145
    'Case    #WERT!
    Case "en-SG": e = ELCID.lcid_en_SG
    Case "es-HN": e = ELCID.lcid_es_HN
    'Case    #WERT!
    Case "en-AE": e = ELCID.lcid_en_AE
    Case "es-NI": e = ELCID.lcid_es_NI
    'Case    "_en_BH" : e = ELCID.'lcid_en_BH
    Case "es-PR": e = ELCID.lcid_es_PR
    'Case    "_en_EG" : e = ELCID.'lcid_en_EG
    Case "es-US": e = ELCID.lcid_es_US
    'Case    "_en_JO" : e = ELCID.'lcid_en_JO
    'Case    "_es_419" : e = ELCID.'lcid_es_419
    'Case    "_en_KW" : e = ELCID.'lcid_en_KW
    Case "es-CU": e = ELCID.lcid_es_CU
    'Case    "_en_TR" : e = ELCID.'lcid_en_TR
    'Case    "_en_YE" : e = ELCID.'lcid_en_YE
    Case "bs-Cyrl": e = ELCID.lcid_bs_Cyrl
    Case "bs-Latn": e = ELCID.lcid_bs_Latn
    Case "sr-Cyrl": e = ELCID.lcid_sr_Cyrl
    Case "sr-Latn": e = ELCID.lcid_sr_Latn
    Case "smn": e = ELCID.lcid_smn
    Case "az-Cyrl": e = ELCID.lcid_az_Cyrl
    Case "sms": e = ELCID.lcid_sms
    Case "zh": e = ELCID.lcid_zh
    Case "nn": e = ELCID.lcid_nn
    Case "bs": e = ELCID.lcid_bs
    Case "az-Latn": e = ELCID.lcid_az_Latn
    Case "sma": e = ELCID.lcid_sma
    'Case    "_kk_Cyrl" : e = ELCID.'lcid_kk_Cyrl
    Case "uz-Cyrl": e = ELCID.lcid_uz_Cyrl
    Case "mn-Cyrl": e = ELCID.lcid_mn_Cyrl
    Case "iu-Cans": e = ELCID.lcid_iu_Cans
    Case "tzm-Tfng": e = ELCID.lcid_tzm_Tfng
    'Case    #WERT!
    Case "zh-Hant": e = ELCID.lcid_zh_Hant
    Case "nb": e = ELCID.lcid_nb
    Case "sr": e = ELCID.lcid_sr
    Case "tg-Cyrl": e = ELCID.lcid_tg_Cyrl
    Case "dsb": e = ELCID.lcid_dsb
    Case "smj": e = ELCID.lcid_smj
    'Case    "_kk_Latn" : e = ELCID.'lcid_kk_Latn
    Case "uz-Latn": e = ELCID.lcid_uz_Latn
    Case "pa-Arab": e = ELCID.lcid_pa_Arab
    Case "mn-Mong": e = ELCID.lcid_mn_Mong
    Case "sd-Arab": e = ELCID.lcid_sd_Arab
    Case "Chr-Cher": e = ELCID.lcid_Chr_Cher
    Case "iu-Latn": e = ELCID.lcid_iu_Latn
    Case "tzm-Latn": e = ELCID.lcid_tzm_Latn
    Case "ff-Latn": e = ELCID.lcid_ff_Latn
    Case "ha-Latn": e = ELCID.lcid_ha_Latn
    Case "ku-Arab": e = ELCID.lcid_ku_Arab
    'Case    #WERT!
    'Case    "_fr_15" : e = ELCID.'lcid_fr_15
    'Case    #WERT!
    'Case    #WERT!
    'Case    #WERT!
    End Select
    ELCID_Parse = e
End Function

Public Function LCIDEnumToStr() As String
    
    Dim hlNam As Collection: Set hlNam = New Collection
    Dim hlVal As Collection: Set hlVal = New Collection
    Dim i As Long, s As String, maxlen As Long
    For i = 1 To 65536
        s = ELCID_ToStr(i)
        If Len(s) Then
            s = Replace(s, "-", "_")
            maxlen = Max(maxlen, Len(s))
            hlNam.Add s
            hlVal.Add i
        End If
    Next
    
    Dim s1 As String
    s1 = "Option Explicit" & vbCrLf & _
        "Public Enum ELCID" & vbCrLf
    For i = 1 To hlNam.Count
        s1 = s1 & "    lcid_" & hlNam.Item(i) & " = &H" & Hex(hlVal.Item(i)) & vbCrLf
    Next
    s1 = s1 & "End Enum" & vbCrLf & vbCrLf
    
    Dim s2 As String
    s2 = s2 & "Public Function ELCID_ToStr(ByVal e As ELCID) As String" & vbCrLf
    s2 = s2 & "    Dim s As String" & vbCrLf
    s2 = s2 & "    Select Case e" & vbCrLf
    For i = 1 To hlVal.Count
        s2 = s2 & "    Case &H" & Hex(hlVal.Item(i)) & ": s = " & """" & Replace(hlNam.Item(i), "_", "-") & """" & vbCrLf
    Next
    s2 = s2 & "    End Select" & vbCrLf
    s2 = s2 & "    ELCID_ToStr = s" & vbCrLf
    s2 = s2 & "End Function" & vbCrLf & vbCrLf
    
    Dim s3 As String
    s3 = s3 & "Public Function ELCID_Parse(s As String) As ELCID" & vbCrLf
    s3 = s3 & "    Dim e As ELCID" & vbCrLf
    s3 = s3 & "    Select Case s" & vbCrLf
    's3 = s3 & "    Case "ar":      e = ELCID.lcid_ar
    For i = 1 To hlVal.Count
        s = hlNam.Item(i)
        s3 = s3 & "    Case " & """" & Replace(s, "_", "-") & """:" & Space(maxlen - Len(s)) & " e = &H" & Hex(hlVal.Item(i)) & vbCrLf
    Next
    s3 = s3 & "    End Select" & vbCrLf
    s3 = s3 & "    ELCID_Parse = e" & vbCrLf
    s3 = s3 & "End Function" & vbCrLf
    LCIDEnumToStr = s1 & s2 & s3
End Function
